name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [page-visit]

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update.py
        run: python update.py